services:
  - type: web
    name: meryenda-store-pos
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        scope: secret
      - key: SESSION_SECRET
        scope: secret
      - key: MONGODB_URI
        scope: secret
    repo: https://github.com/archiecodes42-alt/meryenda-store-login
    branch: main
    rootDir: ./
